server:
  port: 8080
  error:
    include-message: always
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: pt
  datasource:
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
    password: root
    url: jdbc:mysql://localhost:3306/pt
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
rsa:
  private-key: classpath:certs/private_key_pkcs8.pem
  public-key: classpath:certs/public_key.pem
