server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: pt
  datasource:
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
    password: mrd123456
    url: jdbc:mysql://localhost:3306/pt
    username: root